import type {
  BotConfig,
  SendChatMessageParams,
  CreateOrderParams,
  CreatedOrder,
  SseEventData,
} from './types';

// Runtime config via config.js (generated by entrypoint.sh from Railway env vars)
interface RuntimeEnv {
  VITE_API_BASE_URL?: string;
  VITE_APP_NAME?: string;
}

declare global {
  interface Window {
    __ENV__?: RuntimeEnv;
  }
}

function getBaseUrl(): string {
  return (
    window.__ENV__?.VITE_API_BASE_URL ||
    (import.meta.env as unknown as { VITE_API_URL?: string }).VITE_API_URL ||
    'http://localhost:3000'
  );
}

const BASE_URL = getBaseUrl();

async function handleResponse<T>(res: Response): Promise<T> {
  if (!res.ok) {
    const data = await res.json().catch(() => ({}));
    throw new Error(data.message ?? `Error ${res.status}`);
  }
  return res.json();
}

export async function getBotConfig(slug: string, botKey: string): Promise<BotConfig> {
  const res = await fetch(
    `${BASE_URL}/ai/config?slug=${encodeURIComponent(slug)}&botKey=${encodeURIComponent(botKey)}`
  );
  return handleResponse(res);
}

function parseSseChunk(chunk: string): { event: string; data: SseEventData } | null {
  let event = '';
  let dataStr = '';
  for (const line of chunk.split('\n')) {
    if (line.startsWith('event:')) {
      event = line.slice(6).trim();
    } else if (line.startsWith('data:')) {
      dataStr = line.slice(5).trim();
    }
  }
  if (!event) return null;
  try {
    return { event, data: dataStr ? JSON.parse(dataStr) : {} };
  } catch {
    return null;
  }
}

type SseHandler = (data: SseEventData, params: SendChatMessageParams) => boolean;

const textHandler: SseHandler = (data, params) => {
  params.onText?.(data.content ?? '');
  return true;
};

const textResetHandler: SseHandler = (_data, params) => {
  params.onTextReset?.();
  return true;
};

const toolCallHandler: SseHandler = (data, params) => {
  params.onToolCall?.(data.toolName ?? '');
  return true;
};

const orderHandler: SseHandler = (data, params) => {
  params.onOrder?.({
    publicCode: data.publicCode ?? '',
    total: data.total ?? 0,
    items: (data.items ?? []).map(i => ({
      name: i.name,
      quantity: i.quantity,
      unitPrice: i.unitPrice ?? 0,
      subtotal: i.subtotal,
    })),
  });
  return true;
};

const customerHandler: SseHandler = (data, params) => {
  params.onCustomer?.({
    publicCode: data.publicCode ?? '',
    customerName: data.customerName ?? null,
    paymentIntent: data.paymentIntent ?? null,
  });
  return true;
};

const doneHandler: SseHandler = (_data, params) => {
  params.onDone?.();
  return false;
};

const errorHandler: SseHandler = (data, params) => {
  params.onError?.(data.message ?? 'Error desconocido');
  return false;
};

const sseHandlers: Record<string, SseHandler> = {
  text: textHandler,
  text_reset: textResetHandler,
  tool_call: toolCallHandler,
  order: orderHandler,
  customer: customerHandler,
  done: doneHandler,
  error: errorHandler,
};

function handleSseEvent(
  parsed: { event: string; data: SseEventData },
  params: SendChatMessageParams
): boolean {
  const handler = sseHandlers[parsed.event];
  if (!handler) return true;
  return handler(parsed.data, params);
}

export async function sendChatMessage(params: SendChatMessageParams): Promise<void> {
  const res = await fetch(`${BASE_URL}/ai/chat`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(params),
  });
  if (!res.ok) throw new Error('Error enviando mensaje');

  const reader = res.body?.getReader();
  if (!reader) return;

  const decoder = new TextDecoder();
  let buffer = '';
  let shouldContinue = true;

  while (shouldContinue) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split('\n\n');
    buffer = lines.pop() ?? '';
    for (const chunk of lines) {
      const parsed = parseSseChunk(chunk);
      if (parsed && !handleSseEvent(parsed, params)) {
        shouldContinue = false;
        break;
      }
    }
  }
}

export async function createDraftOrder(params: CreateOrderParams): Promise<CreatedOrder> {
  const res = await fetch(`${BASE_URL}/ai/create-order`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(params),
  });
  return handleResponse(res);
}
